init:
  - git config --global core.autocrlf input

before_build:
  - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

platform: Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true
